name: imple CI pipeline

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
   

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a simple command 
      run: echo "This is my pipeline run"

    - name: step 1
      run: echo "This is my frist step 1"

    - name: step 2
      run: echo "This is my second step 2"

    - name: Pipeline Break
      run: echo "pipeline start again"

    - name: Build Docker Image
      run: docker build -t devops .

    - name: login to ghcr.io
      run: echo "${{secrets.GHCR_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      run: docker build -t ghcr.io/${{github.actor}}/devops:v1 .

    - name: Docker push
      run: docker push ghcr.io/${{github.actor}}/devops:v1  